<?php
$data = array (
  0 => 
  array (
    'cat_id' => '35',
    'cat_name' => '葡萄籽靓皙系列',
    'cat_enname' => 'HAFEISI',
    'cat_addtype' => '0',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  1 => 
  array (
    'cat_id' => '36',
    'cat_name' => '紫苏美肌系列',
    'cat_enname' => 'HAFEISI',
    'cat_addtype' => '0',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  2 => 
  array (
    'cat_id' => '34',
    'cat_name' => '菁致奇迹系列',
    'cat_enname' => 'HAFEISI',
    'cat_addtype' => '0',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  3 => 
  array (
    'cat_id' => '33',
    'cat_name' => '西非栅藻系列',
    'cat_enname' => 'HAFEISI',
    'cat_addtype' => '0',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  4 => 
  array (
    'cat_id' => '37',
    'cat_name' => '深海胶原系列',
    'cat_enname' => 'HAFEISI',
    'cat_addtype' => '0',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  5 => 
  array (
    'cat_id' => '38',
    'cat_name' => '红海经典系列',
    'cat_enname' => 'HAFEISI',
    'cat_addtype' => '0',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
);
?>